version: "3.9"

services:
  caddy: &caddy
    image: 90dy/caddy:latest
    build:
      context: .
      dockerfile: caddy.Dockerfile
      target: caddy
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data/caddy
      - ./caddy/config:/config/caddy

  ccxt-app: &ccxt-app
    image: 90dy/ccxt-app:latest
    build:
      context: .
      dockerfile: ccxt-app.Dockerfile
      args:
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    volumes:
      - ./ccxt-app/data:./data
    ports:
      - "127.0.0.1:3000:3000"

