version: "3.9"

services:
  caddy:
    image: 90dy/caddy:latest
    build:
      context: .
      dockerfile: caddy.Dockerfile
      target: caddy
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data/caddy
      - ./caddy/config:/config/caddy
